### ISSUE TITLE
Performance issue for the transposition of a CSR matrix

### ISSUE THREAD

**Issue by GuilloteauQ** [daphne-eu/daphne#794]
Transposing a sparse (CSR) matrix takes ages, orders of magnitude more than the others operations.

Here is a small experimental insight for a matrix of dimensions 1_000_000 x 1_000_000 with varying sparsity (x-axis)

The command:
```
daphne --vec --select-matrix-repr --num-threads 20 ......
```

![grafik](https://github.com/user-attachments/assets/e3927224-7f84-42f2-8072-b170dc786dbd)

Here is the code for the `transpose` column:
```daph
n = 1000000;
A = rand(n, n, 1.0, 1.0, $sparsity, -1);

t1 = now();
B = t(A);
t2 = now();

x = aggMax(B);
print((t2 - t1) / 1000000000.0);
```

Code: 
https://github.com/daphne-eu/daphne/blob/548ea018260b583d7a72b891fd59ad48f3570019/src/runtime/local/kernels/Transpose.h#L89-L120

**Comment by GuilloteauQ** [comment]
If no one has any immediate idea, i can try to investigate

**Comment by GuilloteauQ** [comment]
I implemented the transposition of CSR matrices as in scipy:

https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/scipy/sparse/sparsetools/csr.h#L419-L462

Here is a preliminary comparison of performance: 
- `current` is the current implementation of transpose of CSR matrices
- `new` is this scipy-based implementation
- I tried with 2 scheduling schemes (`STATIC` and `MFSC`)
- several matrix sizes (1_000 x 1_000, to 1_000_000 x 1_000_000 )
- several sparsity values ($10^{-4}$ to $10^{-10}$)

![grafik](https://github.com/user-attachments/assets/fcc6eef2-73b3-4995-b42b-bf5e10fee5aa)

DAPHNE code:
```
# bench.daph
size=$size;
sparsity=$sparsity;

A = rand(size, size, 1.0, 1.0, sparsity, -1);

start = now();

B = t(A);

end = now();
print((end-start) / 1000000000.0);

x = mean(B);
```

CLI:

```
daphne --vec  --num-threads=20 --select-matrix-repr --partitioning=${SCHEME}  --queue_layout=CENTRALIZED\
             --pin-workers --args size=${MATRIX_SIZE} --args sparsity=${SPARSITY}  bench.daph
```

Results look good. There is not much impact for small matrices, but significant improvement of performance for larger matrices.

I still need to clean some things, and I will create a PR with this new implementation

**Comment by corepointer** [comment]
Sorry for the late response and big thanks for going forward with this :+1: 
What's interesting is, why the peak at sparsity 10e-6 (that is still present in the 2nd figure). Also, it looks like the STATIC execution time got worse for the largest size :thinking: 
I don't have any answers atm. Maybe I get to run that code myself soon.
